### PR TITLE
Remove Object.setPrototypeOf polyfill

### PR DESCRIPTION
**Pull request by Phillip9587**
This PR removes the `Object.setPrototypeOf` polyfill, which is no longer needed since this package now requires Node.js v18 as the minimum supported version. All existing tests should pass, as this change only impacts older Node versions no longer supported.

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by wesleytodd** [comment]
Hey, I know I have been slow to review things but I wonder if we could keep things open for a bit longer than a day? This was added originally to support *browsers* and we probably should have had a browser compatibility support listed somewhere and ideally tested, but it was a long time ago and I don't remember the discussions from back then. But to me this should have been considered a breaking change unless we were also going to consider 2.x having dropped browser supports. If we want that (which I think is a good idea) then we should also document this change as if it was part of what we dropped in 2.x.

**Comment by UlisesGascon** [comment]
> but I wonder if we could keep things open for a bit longer than a day?

Yep, l will work on small policy for this and other stuff related to PRs.

>  This was added originally to support browsers and we probably should have had a browser compatibility support listed somewhere and ideally tested, but it was a long time ago and I don't remember the discussions from back then (...)

In this case I think that we are safe as `setPrototypeOf` is super supported since a long time ago https://caniuse.com/mdn-javascript_builtins_object_setprototypeof.

I think that following with the proposal of this policy (https://github.com/expressjs/discussions/pull/289) we should include tests for the things that we actually maintain. So, if the library was "unintended" working fine for the browsers probably we want to include tests for this otherwise "unintended" features might break at any time. Also this applies for any runtime that we don't specifically support, in this scenario I considered the browsers in this category.

**Comment by wesleytodd** [comment]
> In this case I think that we are safe as setPrototypeOf is super supported since a long time ago

Yeah, I totally agree and removing it (and all the other unneeded polyfill type things) is a great thing. I was just being a stickler for semver 🤓.

---

I think we can continue the browser support discussion in #128 and then revisit this once we make a decision there?

**Pull request merged**
