### PR TITLE
Added example of 404/405 handling as discussed in #62

### PR DESCRIPTION
**Pull request by wesleytodd**
If this in fact works then it is a nice addition since it is a bit more complex than the existing examples in the readme.  @whitlockjc Can you update if the solution actually solves your problem?

### CODE REVIEW

**Comment by whitlockjc** [comment]
If I understand this example, I would need to use `.all` for each path.  Is that correct?

**Comment by wesleytodd** [comment]
Yes, that is correct.  I would say you might want to write a little helper to wrap it up:

var route = router.route('/foo')
// add methods...
handle405(route);

**Comment by whitlockjc** [comment]
Yep, that's what I'd do.  Let me give it a shot.

**Comment by wesleytodd** [comment]
Anyone have input on adding examples like this?  @whitlockjc said that the approach worked for his use case.  If no one opposed it would be nice to get this merged?

**Comment by whitlockjc** [comment]
I wish there was a better way to do this, like a single `.all` for all routes.  But this does work as-is, verified.

**Comment by wesleytodd** [comment]
>  not use Express-only syntax

Good call, I will remember this for the future.

**Pull request merged**
