### PR TITLE
Expose router engine for other implementations

### LINKED ISSUE #12: Router Engine
I need to implement a router similar to this one, but with different path matching semantics. Is there any plan to abstract the core logic into an engine module that other implementations can use?

### PR DESCRIPTION
**Pull request by blakeembrey**
There's still a couple of things to decide, but it works wonderfully for what I need and can plug any other implementation in that supports the same function return syntax. Only issue I see is debugging since it currently relies heavily on human-readable paths to be passed to the engine.

Closes #12

### CODE REVIEW

**Comment by blakeembrey** [comment]
@dougwilson Thoughts on an implementation like this?

**Comment by dougwilson** [comment]
Hey, sorry, I've just been busy and haven't been able to look over this changeset yet (it's really big). The only thing I've noticed so far is you deleted a few tests, signaling it's not backwards-compatible, but I haven't look at anything else just yet.

**Comment by blakeembrey** [comment]
@dougwilson It should be backward compatible, those tests were testing implementation details by using `route.path` but that's the same note as the debugging issue I mentioned. Since we're using a function now, testing for `route.path` doesn't make so much sense and neither does logging it. So maybe we add a property to functions that represent `route.path` that can be logged?

**Comment by dougwilson** [comment]
Gotcha. So after the change, what does `req.route` become? It people using it now cannot drop in this change set, then that's by definition not backwards-compatible :)

**Comment by dougwilson** [comment]
For example, there seem to be many, many people using `req.route.path`, but I guess that's missing now? Since it was a publicly-exposed thing, if it's missing and all they did was upgrade this module, it would have to be under a major version bump is all. I'm not saying we cannot, I'm just saying what I saw _so far_ :)

**Comment by blakeembrey** [comment]
The only change is that `req.route.path` no longer exists. If that's an issue with breaking backward compatibility then we could keep passing the path through easily. It'd fix the debugging issues too, to keep passing that around.

**Comment by blakeembrey** [comment]
Ok, good to know. I'll add that functionality back now and ping you again :+1:

**Comment by blakeembrey** [comment]
By the way, one thing I noticed was `strict: false` on `.use` instead of using the `this.strict` option - is that intentional?

**Comment by blakeembrey** [comment]
@dougwilson No backward incompatibility now.

**Comment by blakeembrey** [comment]
@dougwilson Sorry to be so pushy, but I really want to publish a bunch of middleware on top of this functionality this week. Do you have any thoughts on the implementation?

**Comment by dougwilson** [comment]
Sure. Sorry, it's hard to look through " 801 additions and 739 deletions" :) Do you have any documentation of how this new feature would be used? (so I can at least maybe only review the external API :P).

**Comment by dougwilson** [comment]
I also don't completely understand what you're doing with this `truth()` function in a few of the files.

**Comment by blakeembrey** [comment]
The implementation layer is pretty much `index.js` and most of the changes are just moving `index.js` to `engine.js` and making the layers use a match function instead of regexp. It's not actually a lot of changes, but the files moving made it a bit messy (sorry!)

I can also publish the module implementation I've implemented to show you how I'm using it.

**Comment by blakeembrey** [comment]
> I also don't completely understand what you're doing with this truth() function in a few of the files.

Yeah, sorry. Maybe there's a better way to document it, but it's basically the "fast match" route from before that you always expected to match (E.g. `use`). It's a function that always evaluates to true, but I'll think if there's a better implementation. Thoughts?

**Comment by dougwilson** [comment]
> I can also publish the module implementation I've implemented to show you how I'm using it.

That's fine, and we can also exchange it privately if you feel that necessary :) But we'll probably want docs in the readme eventually, haha.

**Comment by blakeembrey** [comment]
I can try my hand at some simple documentation at the bottom of the readme.

**Comment by dougwilson** [comment]
> but I'll think if there's a better implementation. Thoughts?

I don't know enough about the implementation to really comment :)

**Comment by dougwilson** [comment]
From the title:

> Expose router engine for other implementations 

Based on your file names, I would expect that you'd have an exports of `Engine`? I don't see that, though?

**Comment by blakeembrey** [comment]
> Based on your file names, I would expect that you'd have an exports of Engine? I don't see that, though?

Like in `index.js`? I just expected people to `require('router/engine')`, but you wouldn't?

**Comment by dougwilson** [comment]
> I just expected people to require('router/engine'), but you wouldn't?

No, I wouldn't; I don't consider that to be a public API, otheriwse I'd never be free to rearrange any files in my package.

**Comment by blakeembrey** [comment]
> No, I wouldn't; I don't consider that to be a public API, otheriwse I'd never be free to rearrange any files in my package.

That makes sense, maybe there needs to be a `router-engine` module then - which this implements?

**Comment by dougwilson** [comment]
Perhaps, but please don't take it :) I was just wondering. I'm going to be up for a long time tonight, so I'm going to take a serous look at this, because I share the same want as you :)

**Comment by dougwilson** [comment]
Bu yea, don't mind the exports, then :) If it definitely is agreeable that this would be a `route/engine` case, I can easily split it on merge :) I just wanted to make sure you intended to have people use what's in the `./engine` file :)

**Comment by blakeembrey** [comment]
> Perhaps, but please don't take it :) I was just wondering. I'm going to be up for a long time tonight, so I'm going to take a serous look at this, because I share the same want as you :)

Ok, awesome! Thanks so much :smile: I'm looking forward to releasing new modules on top of this functionality :+1:

**Comment by blakeembrey** [comment]
@dougwilson I pushed the module I built that shows how other implementations would use the engine: https://github.com/mulesoft-labs/osprey-router/blob/master/osprey-router.js

**Comment by blakeembrey** [comment]
@dougwilson I ended up building everything on top of this (https://github.com/mulesoft/osprey) in a bet it (or something similar) will eventually exist. The only other thing I need is to be able to skip the rest of the stack which I saw was already an issue in `express`.

**Comment by dougwilson** [comment]
Oh, cool. So yes, there is an open issue in Express, and it's mainly because of the naming of the special string (`router`); I had decided "whatever, let's just do it even if they sounds similar" but then realized that reading "`next('route')`" generally makes sense, "`next('router')`" doesn't really (it's more of a "`exit('router')`" or something). If you can weigh in on the naming, I can get that in, at least, because the implementation itself is simple and straight-forward.

**Comment by blakeembrey** [comment]
Ok, noted. Can't think of anything better than `end/finish/exit` right now.

I'll probably ping you in a few days about the engine, not sure if you've managed to take a look yet :stuck_out_tongue_closed_eyes:

**Comment by blakeembrey** [comment]
@dougwilson Any luck yet?

**Comment by dougwilson** [comment]
I definitely haven't forgotten :) At least recently, getting everything tested for Node.js 0.12 ended up taking priority :D

**Comment by blakeembrey** [comment]
@dougwilson Ping (sorry)

**Comment by blakeembrey** [comment]
@dougwilson Hope it's ok to bother you once again :smile:

**Comment by dougwilson** [comment]
It's always OK and I'm sorry for the delays, of course :(

**Comment by blakeembrey** [comment]
Any chance this will happen or should I look at branching it and doing a new PR myself? @dougwilson

**Comment by dougwilson** [comment]
It'll definitely happen, haha, I'm sorry :( I was doing some things tonight, but without real direction. Let me look into this tonight (at least the contents of this PR) and if nothing substantial comes out of tonight, then I'll just default to accepting whatever dependency you wanted to stand up (or I guess even this refactoring) :)

**Comment by blakeembrey** [comment]
@dougwilson Thanks for the quick response. Didn't quite grok the last sentence, but I'll need to refactor this PR since it won't merge right now. Should we create a separate "engine" module?

**Comment by dougwilson** [comment]
Oh, sorry. So it meant that if I don't have anything done tonight or any valuable feedback, then I'll just end up accepting whatever PR you provide (if that's a PR that just refactors the engine into a file like this one, or as another dependency, then so be it). If it does end up being a dependency, ideally it's in this org, which you are an owner in :)

**Comment by blakeembrey** [comment]
@dougwilson Just rebased, wasn't at painful (luckily). Only reason there was a conflict is because 99% of the logic from `router.js` is now in `engine.js`. I've kept it here for now since the tests are super comprehensive and to do that amount of tests again, I imagine, would end up implementing this router as the example implementation anyway.

**Comment by blakeembrey** [comment]
@dougwilson Ok, done. I copied some tests over, but the bulk of the changes I just made were because I realised there were some simple optimisations to do. Moved `fast_slash` and `decode_param` to be engine implementations, not router implementations and also realised that every router implementation doesn't need to define all the methods, just needs to override `Engine#route`.

**Comment by blakeembrey** [comment]
Actually, I shouldn't be coding at 1am. The reason people needed to implement these specifically was because other implementations can use a different number of arguments. However, they only difference for those users now will be that they can't rely on the methods already set up and can't use the `sanitizeUse` utility I added. I guess the question now is, is it better to be explicit or implicit for other implementors? We can always add a simple note saying that if the implementors accepts a different number of arguments, they need to override the method implementations. Thoughts? Then this is done :smile:

**Comment by dougwilson** [comment]
Nice! And yes, that is my main concern: that the changes fit into a case where people can use it to build upon :)

**Comment by blakeembrey** [comment]
@dougwilson Well, if it helps, we've been using it in https://www.npmjs.com/package/osprey-router for the past few months. All the methods can be overridden if you need to support for arguments and I'll make that note in the README tomorrow. I'll remove the method implementations by default and add it back to the example, instead exposing the array from `methods` for implementors. Was there anything else you were thinking about?

**Comment by blakeembrey** [comment]
@dougwilson Ok, all done and dusted. The sample implementation in the README should be adequate for anyone else to get started.

**Comment by blakeembrey** [comment]
@dougwilson Have you had any more time to review this at all? Would love to re-open the discussion around unicode URLs once this is merged.

**Comment by blakeembrey** [comment]
@dougwilson Any chance you could review this before too many more changes continue happening :stuck_out_tongue_closed_eyes:

**Comment by blakeembrey** [comment]
@dougwilson :pray:

**Comment by dougwilson** [comment]
Sorry, I have just been so busy herding all these modules around :) I just finished looking through a lot of the Express 4.x issues, so this is on my backlog after getting 4.13.0 out to get this up to snuff and then into the 5.x branch of Express very soon to get a 5.0 beta out! I consider this issue a blocker to 5.0 beta and we really need to get 5.0 out next month, so I hope that signals the importance/timeline of this issue :)

**Comment by blakeembrey** [comment]
@dougwilson Just rebased back against the latest `master` release. Still looking forward to merge :stuck_out_tongue_winking_eye:

I just realised (maybe I did before) but this module still uses `path-to-regexp@0.1.x`. Shouldn't it be using `1.x` now? Or will that be updated before the `5.0` release with this?

**Comment by blakeembrey** [comment]
@dougwilson Rebased against `1.1.3`. Anything I can do to speed this along? By the way, the best way to diff this is to compare the new `engine.js` against the old `index.js`. That should make diffing it easier, since things are pretty much the same minus a couple of parts to decouple the engine.

**Comment by blakeembrey** [comment]
@dougwilson I need to continue working on this branch for promise support and router exiting, so I'm going to close this and reopen under a new PR.

**Pull request closed without merging**
